# Site settings
title: Sinsiroad
email: contact@sinsiroad.com
url: https://sinsiroad.github.io
description: "Moe Game Development Team"
meta_author: HALAK SHIN

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sinsiroad
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: naver
    url: https://twitter.com/sinsiroad/
  - title: twitter
    url: https://twitter.com/sinsiroad/
  - title: facebook
    url:
  - title: github
    url: http://github.com/sinsiroad

# Postal address (add as many lines as necessary)
address:
  - line: 112, Dongtanjiseong-ro, Hwaseong-si
  - line: Gyeonggi-do, 18434, Rep. of KOREA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
